version: "3.7"
services:
  peer:
    build:
      context: .
      dockerfile: docker/DockerfilePeer
    image: peer
    working_dir: /work

  runner:
    depends_on:
      - peer
    build:
      context: .
      dockerfile: docker/DockerfileRunner
    image: runner
    working_dir: /work
